### PR TITLE
Removed/ignored commonly re-generated files

### PR DESCRIPTION
**Pull request by Quix0r**
Don't distribute these files as they got modified on other systems then your own. Better is to ignore them.

You now have to run ./autogen.sh

Added missing README (symlink):

Makefile.am: error: required file './README' not found

### CODE REVIEW

**Comment by Quix0r** [comment]
You may also want to remove the "./configure" step from autogen.sh as people would like to specify other parameters, like --prefix=/opt which is recommended to avoid mixing files from distribution packages and 3rd party files like this one.

**Comment by rpodgorny** [comment]
hi! thanks a lot, i'll take a look at this, soon.

anyway, are you aware of the https://github.com/rpodgorny/uptimed/tree/autotools-cleanup branch? i've already started the works on cleaning up the autogenerated stuff.

**Comment by rpodgorny** [comment]
i've merged my autotools-cleanup branch which does effectively the same. thank you, anyway!

**Comment by Quix0r** [comment]
Welcome. :-)

**Pull request closed without merging**
